trigger: none

variables:
  imageName: 'reachabilitydemo'
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: 'Build and Push Image'
    jobs:
      - job: Build
        displayName: 'Build'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - task: Docker@2
          displayName: 'Build and Push Docker image'
          inputs:
            containerRegistry: '$(dockerConnection)'
            repository: '$(imageName)'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: |
              $(tag)
  
  - stage: Deploy
    displayName: 'Deploy to Kubernetes'
    dependsOn: Build
    condition: succeeded()
    jobs:
    - job: Deploy
      displayName: 'Deploy'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - checkout: self
      
      - task: AzureCLI@2
        displayName: 'Update and Deploy Deployment YAML'
        inputs:
          azureSubscription: '$(subscription)'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            #!/bin/bash
            az aks get-credentials --resource-group $(resourceGroup) --name $(clusterName)
            fullImageName=$(containerRegistry)/$(imageName):$(tag)
            sed -i "s|IMAGE_NAME_PLACEHOLDER|$fullImageName|g" deployment.yaml
            kubectl apply -f deployment.yaml --validate=false
          arguments: |
            --containerRegistry $(containerRegistry)
            --imageName $(imageName)
            --tag $(tag)
